# Generated by Django 5.0.5 on 2024-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Account Team'), ('2', 'Manager'), ('3', 'Admin')], default='ACCOUNT_TEAM', max_length=50),
        ),
    ]
