# Generated by Django 5.0.5 on 2024-05-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_cashin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_source_list', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source_list', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_list', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installment 1 Amount'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_1_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment 1 Date'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installment 2 Amount'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment 2 Date'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installment 3 Amount'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_3_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment 3 Date'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Installment 4 Amount'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='installment_4_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment 4 Date'),
        ),
        migrations.AddField(
            model_name='cashin',
            name='num_installments',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Number of Installments'),
        ),
        migrations.AlterField(
            model_name='cashin',
            name='income_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.incomesource'),
        ),
        migrations.AlterField(
            model_name='cashin',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.project'),
        ),
    ]
