# Generated by Django 5.0.5 on 2024-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_remove_cashin_installment_1_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesource',
            old_name='expense_source_list',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='incomesource',
            old_name='income_source_list',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_list',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cashin',
            name='num_installments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
