# Generated by Django 5.0.5 on 2024-05-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0009_cashin_admin_alter_cashin_income_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashin',
            name='num_installments',
        ),
    ]
