# Generated by Django 5.0.5 on 2024-05-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_remove_cashin_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashin',
            name='cost_center',
            field=models.CharField(blank=True, choices=[('catalyst', 'Catalyst'), ('oil_and_gas', 'Oil and Gas'), ('general_chemicals', 'General Chemicals'), ('overhead', 'Overhead')], default='catalyst', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashin',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashflow.project'),
        ),
    ]
