# Generated by Django 5.0.5 on 2024-05-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_alter_cashin_cost_center_alter_cashin_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Scheduled', 'Scheduled')], default='Received', max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('cost_center', models.CharField(blank=True, choices=[('catalyst', 'Catalyst'), ('oil_and_gas', 'Oil and Gas'), ('general_chemicals', 'General Chemicals'), ('overhead', 'Overhead')], default='catalyst', max_length=50, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('installment', models.IntegerField(choices=[(1, '1 Installment'), (2, '2 Installments'), (3, '3 Installments'), (4, '4 Installments'), (5, '5 Installments'), (6, '6 Installments')], default=1)),
                ('installment_date', models.DateField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashflow.expensesource')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashflow.project')),
            ],
        ),
    ]
