# Generated by Django 5.0.5 on 2024-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_remove_cashout_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Scheduled', 'Scheduled')], default='Received', max_length=50),
        ),
    ]
