# Generated by Django 5.0.5 on 2024-05-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0016_cashout_total_installment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashout',
            old_name='installments',
            new_name='installment_details',
        ),
    ]
