# Generated by Django 5.0.5 on 2024-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0017_rename_installments_cashout_installment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='cashout',
            name='balance_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='cost_center',
            field=models.CharField(blank=True, choices=[('catalyst', 'Catalyst'), ('oil_and_gas', 'Oil and Gas'), ('general_chemicals', 'General Chemicals'), ('overhead', 'Overhead')], default='catalyst', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Scheduled', 'Scheduled')], default='Paid', max_length=50),
        ),
    ]
