# Generated by Django 5.0.5 on 2024-05-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_summary_cashout_balance_to_pay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_inventory', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_inventory', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.project')),
            ],
        ),
    ]
