# Generated by Django 5.0.5 on 2024-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0019_inventory_projectsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
