# Generated by Django 5.0.5 on 2024-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0020_delete_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsummary',
            old_name='total_cash_in',
            new_name='cash_in',
        ),
        migrations.RenameField(
            model_name='projectsummary',
            old_name='total_cash_out',
            new_name='cash_out',
        ),
    ]
